version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: springboot-poc-postgres
    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: pocuser
      POSTGRES_PASSWORD: pocpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
